config/routes.rb
Rails.application.routes.draw do

  resources :user_mail_boxes

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  root'listings#index'
  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'pages/about'
  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

end

app/models/user_mail_box.rb
class UserMailBox < ActiveRecord::Base
end

app/controllers/user_mail_boxes_controller.rb
class UserMailBoxesController < ApplicationController
  before_filter :logged_in_user?,:only => [:new,:create]

  # POST /user_mail_boxes
  # POST /user_mail_boxes.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_letter(user).deliver_now
        format.html { redirect_to(@user, notice: 'User mail box was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/user_mail_boxes_helper.rb
module UserMailBoxesHelper
end

app/views/user_mail_boxes/_form.html.erb
<%= form_for(@user_mail_box) do |f| %>
  <% if @user_mail_box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_mail_box.errors.count, "error") %> prohibited this user_mail_box from being saved:</h2>

      <ul>
      <% @user_mail_box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_mail_boxes/edit.html.erb
<h1>Editing user_mail_box</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_mail_box %> |
<%= link_to 'Back', user_mail_boxes_path %>

app/views/user_mail_boxes/index.html.erb
<h1>Listing user_mail_boxes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_mail_boxes.each do |user_mail_box| %>
      <tr>
        <td><%= user_mail_box.name %></td>
        <td><%= user_mail_box.email %></td>
        <td><%= user_mail_box.login %></td>
        <td><%= link_to 'Show', user_mail_box %></td>
        <td><%= link_to 'Edit', edit_user_mail_box_path(user_mail_box) %></td>
        <td><%= link_to 'Destroy', user_mail_box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User mail box', new_user_mail_box_path %>

app/views/user_mail_boxes/new.html.erb
<h1>New user_mail_box</h1>

<%= render 'form' %>

<%= link_to 'Back', user_mail_boxes_path %>

app/views/user_mail_boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_mail_box.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user_mail_box.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user_mail_box.login %>
</p>

<%= link_to 'Edit', edit_user_mail_box_path(@user_mail_box) %> |
<%= link_to 'Back', user_mail_boxes_path %>